/** 첫 부팅(글 0건)에서만 넣는 예시 글. 기존 로컬 데모에 있던 것과 같은 내용이다. */
export const SEED_POSTS = [
  {
    noticeId: 'n47',
    category: '개발호재',
    title: '분당 재건축 분위기, 요즘 체감상 어떤가요?',
    author: '분당10년차',
    content:
      '선도지구 지정 이후로 동네 부동산 문의가 확 늘었다고 하네요. 실제로 사시는 분들 체감은 어떠신지 궁금합니다.',
    createdAt: '2026-09-12T09:12:00+09:00',
    likes: 14,
    comments: [
      {
        author: '이매동주민',
        content: '주말에 임장 다니는 분들 많아졌어요. 다만 아직 실거래는 잠잠한 편입니다.',
        createdAt: '2026-09-12T11:03:00+09:00',
      },
    ],
  },
  {
    noticeId: 'n47',
    category: '청약문의',
    title: '청약통장 24개월 조건이면 특별공급도 같은 기준인가요?',
    author: '익명',
    content: '공고문에 가입 24개월 이상으로 되어 있는데, 신혼부부 특별공급도 동일하게 보면 되는지 헷갈리네요.',
    createdAt: '2026-09-13T20:41:00+09:00',
    likes: 6,
    comments: [],
  },
  {
    noticeId: 'n40',
    category: '생활정보',
    title: '검암역 주변 병원·마트 이용 후기',
    author: '검단맘',
    content: '입주 6개월째인데 대형마트는 차로 15분, 소아과는 아직 대기가 좀 있어요. 그래도 점점 나아지는 중입니다.',
    createdAt: '2026-09-09T14:20:00+09:00',
    likes: 21,
    comments: [{ author: '예비입주자', content: '좋은 정보 감사해요 :)', createdAt: '2026-09-10T08:15:00+09:00' }],
  },
  {
    noticeId: 'n42',
    category: '분위기',
    title: '월곡 쪽 밤에 다니기 괜찮나요?',
    author: '익명',
    content: '직장이 성수라 출퇴근은 괜찮을 것 같은데, 단지 주변 야간 분위기나 소음은 어떤지 궁금합니다.',
    createdAt: '2026-09-11T22:05:00+09:00',
    likes: 9,
    comments: [],
  },
  {
    noticeId: 'n48',
    category: '개발호재',
    title: '화서역 스타필드 이후로 생활권 많이 바뀌었나요?',
    author: '수원살이',
    content: '주말마다 사람이 많아져서 차는 좀 막히는데, 대신 웬만한 건 동네에서 다 해결됩니다.',
    createdAt: '2026-09-08T18:30:00+09:00',
    likes: 12,
    comments: [
      { author: '정자동', content: '평일 저녁은 한산해요. 주말 낮만 피하면 괜찮습니다.', createdAt: '2026-09-08T21:02:00+09:00' },
    ],
  },
  {
    noticeId: 'n53',
    category: '청약문의',
    title: '신혼·신생아 매입임대 상시 접수인가요?',
    author: '용인예비',
    content: '마감일이 따로 안 적혀 있는데 수시 모집인지, 아니면 공고문에 별도 일정이 있는지 아시는 분 계실까요?',
    createdAt: '2026-09-14T10:11:00+09:00',
    likes: 4,
    comments: [],
  },
];
